workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      node: 22
      java: 21
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Build web project
        script: npm run build
      - name: Generate Capacitor Assets
        script: |
          rm -rf android/app/src/main/res/mipmap-*/*.png
          rm -rf android/app/src/main/res/drawable-*/*.png
          rm -rf android/app/src/main/res/drawable/*.png
          rm -rf android/app/src/main/res/mipmap-anydpi-v26
          npx @capacitor/assets generate --assetPath assets
      - name: Sync Capacitor Android project
        script: npx cap sync android
      - name: Build Android App
        script: |
          cd android
          gradle wrapper
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - rbholakiya@gmail.com
